import json

def make_filing_json(
    ticker: str,
    cik: str,
    company_name: str,
    filing_date: str,
    accession: str,
    primary_doc: str,
    **item_texts
) -> str:
    """
    사용 예:
    make_filing_json(
        ticker="C",
        cik="0000831001",
        company_name="Citigroup Inc.",
        filing_date="2024-12-31",
        accession="0000831001-24-000067",
        primary_doc="c-20241231.htm",
        item1=item1_text,
        item1a=item1a_text,
        item7=item7_text,
        item7a=item7a_text,
    )
    처럼 호출하면 됨.

    item_texts에는 item1, item1a, item7, item7a 같은 키워드를 마음대로 넣을 수 있음.
    """

    data = {
        "ticker": ticker,
        "cik": cik,
        "company_name": company_name,
        "filing_date": filing_date,
        "accession": accession,
        "primary_doc": primary_doc,
        "item_sections": item_texts,  # {"item1": "...", "item1a": "...", ...}
    }

    # json.dumps가 " 와 줄바꿈(\n) 같은 걸 전부 JSON 규격에 맞게 escape해 줌
    return json.dumps(data, ensure_ascii=False, indent=2)
item1_text = """FORWARD-LOOKING STATEMENTS
 
The information in this Form 10-K contains forward-looking statements about future events and circumstances and their effects upon revenues, expenses and business opportunities. Generally speaking, any statement in this Form 10-K not based upon historical fact is a forward-looking statement. Forward-looking statements can also be identified by the use of forward-looking or conditional words, such as “could,” “should,” “can,” “continue,” “aim,” “estimate,” “forecast,” “intend,” “look,” “may,” “will,” “expect,” “believe,” “anticipate,” “plan,” “remain,” “confident”, “commit,” “enable,” “potential” and “trajectory” or similar expressions. In particular, statements regarding the Company's plans, strategies, prospects and expectations regarding its business and industry, as well as environmental and social impact initiatives and similar commitments, are forward-looking statements. They reflect expectations, are not guarantees of performance and speak only as of the dates the statements are made. These forward-looking statements involve a number of risks and uncertainties. Factors that could cause actual results to differ materially from those in the forward-looking statements include those reflected in the Risk Factors section on page 28 of this Form 10-K and elsewhere in the Company's filings with the SEC. Except as required by law, the Company does not undertake to update such forward-looking statements. You should not rely unduly on forward-looking statements.
ABOUT McDONALD'S
 
McDonald’s Corporation, the registrant, together with its subsidiaries, is referred to herein as the "Company." The Company, its franchisees and suppliers are referred to herein as the "System."
BUSINESS SUMMARY
GENERAL
For the year ended December 31, 2024, there were no material changes to the Company's corporate structure or in its method of conducting business. Refer to the Segment and Geographic Information section on page 52 of this Form 10-K for additional information.
DESCRIPTION OF THE BUSINESS
The Company franchises and owns and operates McDonald’s restaurants, which serve a locally relevant menu of quality food and beverages in communities across more than 100 countries. Of the 43,477 McDonald's restaurants at year-end 2024, approximately 95% were franchised.
The Company’s reporting segments are aligned with its strategic priorities and reflect how management reviews and evaluates operating performance. Significant reportable segments include the United States ("U.S.") and International Operated Markets. In addition, there is the International Developmental Licensed Markets & Corporate segment, which includes the results of over 75 countries as well as Corporate activities.
McDonald’s franchised restaurants are owned and operated under one of the following structures - conventional franchise, developmental license or affiliate. The optimal ownership structure for an individual restaurant, trading area or market (country) is based on a variety of factors, including the availability of individuals with entrepreneurial experience and financial resources, as well as the local legal and regulatory environment in critical areas such as property ownership and franchising. The business relationship between the Company and its independent franchisees is supported by adhering to standards and policies, including McDonald's Global Brand Standards, and is of fundamental importance to overall performance and to protecting the McDonald’s brand.
The Company is primarily a franchisor and believes franchising is paramount to delivering great-tasting food, locally relevant customer experiences and driving profitability. Franchising enables an individual to be their own employer and maintain control over all employment related matters, marketing and pricing decisions, while also benefiting from the strength of McDonald’s global brand, operating system and financial resources.
Directly operating McDonald’s restaurants contributes significantly to the Company's ability to act as a credible franchisor. One of the strengths of the franchising model is that the expertise from Company-owned and operated restaurants allows McDonald’s to improve the operations and success of all restaurants while innovations from franchisees can be tested and, when viable, efficiently implemented across relevant restaurants. Having Company-owned and operated restaurants provides Company personnel with a venue for restaurant operations training experience. In addition, in our Company-owned and operated restaurants, and in collaboration with franchisees, the Company is able to further develop and refine operating standards, marketing concepts and product and pricing strategies.
The Company’s revenues consist of sales by Company-owned and operated restaurants and fees from franchised restaurants operated by conventional franchisees, developmental licensees and affiliates. Fees vary by type of site, amount of Company investment, if any, and local business conditions. These fees, along with occupancy and operating rights, are stipulated in franchise/license agreements that generally have 20-year terms. The Company’s Other revenues are comprised of fees paid by franchisees to recover a portion of costs incurred by the Company for various technology platforms, revenues from brand licensing arrangements to market and sell consumer packaged goods using the McDonald’s brand and, for periods prior to its sale on April 1, 2022, third-party revenues for the Company's Dynamic Yield business.
Conventional Franchise
Under a conventional franchise arrangement, the Company generally owns or secures a long-term lease on the land and building for the restaurant location and the franchisee pays for equipment, signs, seating and décor. The Company believes that ownership of real estate, combined with the co-investment by franchisees, enables it to achieve restaurant performance levels that are among the highest in the industry.


McDonald's Corporation 2024 Annual Report 3



Franchisees are responsible for reinvesting capital in their businesses over time. In addition, to accelerate implementation of certain initiatives, the Company may co-invest with franchisees to fund improvements to their restaurants or operating systems. These investments, developed in collaboration with franchisees, are designed to cater to consumer preferences, improve local business performance and increase the value of the McDonald's brand through the development of modernized, more attractive and higher revenue generating restaurants.
The Company requires franchisees to meet rigorous standards and generally does not work with passive investors. The business relationship with franchisees is designed to facilitate consistency and high quality at all McDonald’s restaurants. Conventional franchisees contribute to the Company’s revenue, primarily through the payment of rent and royalties based upon a percent of sales, with specified minimum rent payments, along with initial fees paid upon the opening of a new restaurant or grant of a new franchise. The Company's heavily franchised business model is designed to generate stable and predictable revenue, which is largely a function of franchisee sales, and resulting cash flow streams.
Developmental License or Affiliate
Under a developmental license or affiliate arrangement, licensees are responsible for operating and managing their businesses, providing capital (including the real estate interest) and developing and opening new restaurants. The Company generally does not invest any restaurant capital under a developmental license or affiliate arrangement, and it receives a royalty based on a percent of sales, and generally receives initial fees upon the opening of a new restaurant or grant of a new license.
While developmental license and affiliate arrangements are largely the same, affiliate arrangements are used in a limited number of foreign markets (primarily China and Japan) within the International Developmental Licensed Markets & Corporate segment as well as a limited number of individual restaurants within the International Operated Markets segment, where the Company also has an equity investment and records its share of net results in equity in earnings of unconsolidated affiliates.
PURPOSE, MISSION AND VALUES
Through its size and scale, McDonald's embraces and prioritizes its role and commitment to the communities in which it operates through its purpose to feed and foster communities, and its mission to make delicious feel-good moments easy for everyone. The Company is guided by five core values that define who it is and how it runs the business across the three-legged stool of McDonald’s franchisees, suppliers, and employees:
1.Serve – We put our customers and people first;
2.Inclusion – We open our doors to everyone;
3.Integrity – We do the right thing;
4.Community – We are good neighbors; and
5.Family – We get better together.
The Company believes that its people, all around the world, set it apart and bring these values to life daily.
HUMAN CAPITAL MANAGEMENT
The Company’s people strategies aim to support an inclusive environment that represents the communities in which it operates. To do this, the Company offers quality training and learning opportunities and upholds high standards of health and safety designed to create and maintain a safe and respectful workplace for its employees. In support of the Company’s values, the Company’s annual incentive plan holds the Chief Executive Officer ("CEO") and Executive Officers accountable for efforts that drive employee engagement and our values.
You can find more information about the Company's human capital management and related initiatives in our 2023-2024 Purpose & Impact Report and on the “Our Purpose & Impact” section of the Company’s website.
People
Company employees, which include those in the Company's corporate and other offices as well as in Company-owned and operated restaurants, totaled over 150,000 worldwide as of year-end 2024, of which approximately 70% were based outside of the U.S. In addition to Company employees, the over two million individuals who work in McDonald's franchised restaurants around the world are critical to the Company’s success, enabling it to drive long-term value creation and further its purpose and mission. People are at the cornerstone of the Company's business and an essential part of the System.
Commitment to Inclusion
Inclusion is one of the Company’s core values, which it strives to integrate into business operations to deliver an inclusive experience for stakeholders—including employees, franchisees, suppliers, customers and the communities in which the Company operates.
Grounded in the Company's values, the Company believes in treating everyone with dignity, fairness and respect, always. There are four guiding principles the Company applies to evaluate its work: (i) our system thrives when we are shaped by the communities in which we operate, (ii) our early and full adoption of inclusion gives us a competitive advantage, (iii) individuals perform their best when they feel they belong and (iv) our priority is to be a responsible business, acting lawfully and being responsive to the business environment.
Safe & Respectful Workplaces
The Company believes that it has a responsibility to help protect the health and safety of anyone who works at or enters a McDonald’s restaurant, a concept that is incorporated into Company policies, codes of conduct and guiding principles. The Company is committed to promoting safety in all of the Company’s corporate and other offices and Company-owned and operated restaurants, as well as supporting franchisees to do the same in the restaurants they own and operate. The Company also works to foster respectful workplaces, where people can be themselves without fear of harassment, discrimination, retaliation or violence, and to help its franchisees do the same in their workplaces.

McDonald's Corporation 2024 Annual Report 4



The Company's Global Brand Standards (which apply to all McDonald’s restaurants, whether Company-owned and operated or franchised) prioritize action in four key areas: protecting employee health and safety, preventing workplace violence, preventing harassment, discrimination and retaliation, and listening through restaurant employee feedback.
The Company's existing procedures include several ways that an individual can report an incident or raise a concern. The Company requires all restaurants to maintain their own reporting process. In addition, the Global Business Integrity Line is available to anyone and allows for concerns to be reported anonymously.
The Company also strives to weave human rights into its day-to-day practices, helping fulfill its commitment to respect the rights of all people and communities who produce, serve, and enjoy McDonald’s food. The Company’s commitment to respect human rights is set out in its Human Rights Policy and is in line with the United Nations Guiding Principles on Business and Human Rights (UNGPs). In addition to the Human Rights Policy, the Company has standards, principles and policies to reinforce a culture of integrity and respect, forming the foundation of its efforts to feed and foster communities worldwide. As part of its efforts to promote respect for human rights through its standards, the Company has specifically set policies and guidance to help address and protect populations that may be most vulnerable to human rights violations. For example, the Company’s Responsible and Ethical Recruitment Principles outline standards to prevent the exploitation of migrant workers and ensure responsible recruitment for this population at all McDonald’s restaurants. Additional information about the Company’s human rights approach and focus areas, as well as related policies and standards, can be found on the "Human Rights" section of the Company's website.
Compensation, Benefits, and Talent Development
The compensation and benefits provided to Company employees, including both corporate staff and Company-owned and operated restaurant employees, are established based upon competitive considerations in the relevant labor market. The amount and type of compensation varies by an employee's level and location, and typically includes some combination of the following (in addition to base pay): cash bonuses, stock-based awards, retirement savings programs, and health and welfare benefits. Company employees may also receive paid time off, family care resources, tuition assistance and flexible work schedules.
In 2021, the Company publicly communicated its ongoing commitment to equal pay, which is supported by an annual pay gap analysis that aims to ensure equitable pay practices are consistently implemented and executed across the Company.
Results of the 2024 pay gap analysis demonstrated our commitment by showing that women globally in Company-owned and operated markets were paid 99.93 cents on the dollar in base pay on average of what men were paid for similar work. Further, there was no base pay gap disfavoring underrepresented groups in the U.S. These results indicate the Company substantially attained equal pay, and in 2025 intends to continue its commitment to close pay gaps identified in annual equal pay analyses.
The Company follows Global Pay Principles to ensure that fair pay practices are understood and consistently implemented for all Company employees; these principles enforce its understanding that pay should be competitive, non-discriminatory, performance-based, understandable, and compliant with all applicable legal and regulatory requirements and standards.
Additionally, the Company has a long-standing commitment to providing training, education benefits and career path opportunities that empower its people. Learning and development is a competitive advantage to McDonald’s and a true differentiator to its employee value proposition. McDonald’s Hamburger University has multiple learning centers around the world, as well as online resources, that provide training for Company employees, as well as franchisees and their eligible employees. The Company is committed to providing opportunities for people to enhance their skills and fulfill their potential through talent development programs, apprenticeship opportunities, and language and technical skill training and support for continuing education, as it believes this helps to facilitate talent attraction, career development, and retention.
Communities
The Company aims to build strong and inclusive connections that deliver on the needs of the communities McDonald’s serves, because the Company believes that doing so is consistent with the Company’s business objectives and values. The Company is focused on partnering with organizations that share the Company’s core values, harnessing its size and influence to help maximize collective impact, while also strengthening relationships with the communities in which it operates. The Company’s strategy focuses on three key strategic outcome areas - Supporting Families, Times of Need, and Opportunity Employment.
The Company is proud to support Ronald McDonald House Charities (“RMHC”) and their global network of over 255 local chapters in more than 60 countries and regions in their mission to provide essential services to remove barriers, strengthen families and promote healing when children need healthcare. In 2024, the Company delivered against its five-year, $100 million commitment to RMHC.
McDonald's creates opportunities that encourage Company employees, franchisees and their employees, suppliers, and customers to get involved in philanthropic and volunteering opportunities.
PURPOSE & IMPACT
The Company prioritizes the environmental, social and governance issues that are of the highest importance to its stakeholders and where it believes the business can have the greatest impact to create long-term, sustainable value. The Company’s Impact Strategy is centered around four Impact Areas: Our Planet; Food Quality & Sourcing; Jobs, Inclusion & Empowerment; and Community Connection. Within these Impact Areas, the Company has established certain strategies, goals, policies and performance indicators. The Company periodically reports progress on the “Purpose & Impact” section of its website.
The Company monitors the evolving environmental landscape to further understand potential risks and opportunities for the business in collaboration with expert partners. The Company believes taking action on environmental matters will drive long-term business value by ensuring that it is managing operational costs in its energy supply, improving the security of its raw material supply, stewarding the environment in its surrounding communities and reducing its exposure to increasing environmental risks, regulation and costs.

McDonald's Corporation 2024 Annual Report 5



SUPPLY CHAIN, FOOD SAFETY AND QUALITY
The Company and its franchisees purchase food, packaging, equipment, and other goods from numerous independent suppliers. The Company has established and enforces high food safety and quality standards. The quality management systems and processes involve ongoing product reviews, supplier visits and third-party verifications with performance expectations. The Company requires periodic third-party food safety audits of suppliers to verify compliance with its food safety and quality standards. The audits help ensure that suppliers are meeting McDonald’s Supplier Quality Management System (SQMS) standards. In addition, the Company promotes the consistency of its core menu by regular sensory evaluations and calibration trainings. A digital transformation project is underway to promote data excellence and continuous measures on quality and food safety performance. A Food Safety Advisory Council, comprised of the Company’s internal food safety experts as well as suppliers and outside experts, supports the Company’s food safety risk management work and provides strategic global leadership for all aspects of food safety and quality. The Company also has ongoing programs to elevate food safety culture throughout the business by educating employees about food safety practices, including proper storage, handling and preparation of food for customers, and conducting trainings for its suppliers and restaurant operators to share best practices on food safety and quality.
The Company collaborates with suppliers to encourage innovation and drive continuous improvement across its global supply chain. The Company also works closely with suppliers and other third-party experts to drive sustainable sourcing initiatives and to improve the health and welfare of the animals within its supply chain. Led by its Global Chief Supply Chain Officer, the Company has a comprehensive strategy that its global supply chain organization leverages to identify, assess, and manage risk in its supply chain.
To reinforce the importance of its values, the Company maintains a Supplier Code of Conduct that applies to all of its suppliers. The Company expects all of its suppliers to meet the rigorous standards set forth in the Code, which cover areas including human rights, workplace environment, business integrity and environmental management. In addition, the Company has a comprehensive Supplier Workplace Accountability (SWA) program to help suppliers understand its expectations, verify compliance and work toward continuous improvement.
PRODUCTS
McDonald’s restaurants offer a substantially uniform menu, although there are geographic variations to suit local consumer preferences and tastes.
McDonald’s menu features hamburgers and cheeseburgers, the Big Mac, the Quarter Pounder with Cheese, the Filet-O-Fish, and several chicken sandwiches like the McChicken, McCrispy and McSpicy, as well as Chicken McNuggets, World Famous Fries, shakes, McFlurry frozen desserts, sundaes, soft serve cones, cookies, pies, soft drinks, coffee, McCafé beverages and other beverages.
McDonald’s restaurants in the U.S. and many international markets offer a full or limited breakfast menu. Breakfast offerings may include breakfast sandwiches, such as the Egg McMuffin, Sausage McMuffin with Egg and McGriddles, biscuit and bagel sandwiches, oatmeal, hash browns, breakfast burritos and hotcakes.
In addition to these menu items, restaurants sell a variety of other products during limited-time promotions.
Taste, quality, choice, value and nutrition are important to customers, and the Company is continuously evolving its menu to meet its customers' needs, including testing new products on an ongoing basis.
MARKETING
McDonald’s global brand is well known. Marketing, promotional and public relations activities are designed with customers in mind and are focused on promoting the McDonald’s brand and differentiating the Company from its competitors. Marketing and promotional efforts focus on value, quality, food taste, menu choice, nutrition, convenience, cultural relevance and the customer experience.
INTELLECTUAL PROPERTY
The Company owns or is licensed to use valuable intellectual property, including trademarks, service marks, patents, copyrights, trade secrets and other proprietary information. The Company considers the "McDonald's" trademark and the Golden Arches Logo to be of material importance to its business. Depending on the jurisdiction, trademarks and service marks generally are valid as long as they are used and/or registered. The Company's patents, copyrights and licenses are of varying durations.
COMPETITION
McDonald’s restaurants compete with international, national, regional and local retailers of traditional, fast casual and other food service competitors. The Company measures its competitive position within the informal eating out ("IEO") segment, which is inclusive of the Company's primary competition of quick-service restaurants, but also includes 100% home delivery/takeaway providers, convenience stores, street stalls or kiosks, cafés, specialist coffee shops, self-service cafeterias and juice/smoothie bars. The Company competes among quick-service restaurants primarily on the basis of price, convenience, service, experience, menu variety and product quality.
GOVERNMENT REGULATIONS
The Company has global operations and is therefore subject to the laws of the United States and many foreign jurisdictions in which it operates and the rules and regulations of various governing bodies, which may differ among jurisdictions. As discussed under “Legal Proceedings – Government Regulations” on page 37 of this Form 10-K, governments have adopted laws and regulations involving various aspects of the restaurant business, including, but not limited to, advertising, franchising, health, safety, environment, competition, zoning, employment and taxation.
While costs associated with legal and regulatory compliance have increased along with the number and scope of laws and regulations affecting our business, these costs are not expected to have a material effect on the Company’s capital expenditures, earnings or competitive position.
"""

item1a_text = """RISK FACTORS
 
Cautionary Statement Regarding Forward-Looking Statements
The information in this report contains forward-looking statements about future events and circumstances and their effects upon revenues, expenses and business opportunities. Generally speaking, any statement in this report not based upon historical fact is a forward-looking statement. Forward-looking statements can also be identified by the use of forward-looking or conditional words, such as “could,” “should,” “can,” “continue,” “aim,” “estimate,” “forecast,” “intend,” “look,” “may,” “will,” “expect,” “believe,” “anticipate,” “plan,” “remain,” “confident,” “commit,” “enable,” “potential” and "trajectory" or similar expressions. In particular, statements regarding our plans, strategies, prospects and expectations regarding our business and industry are forward-looking statements. They reflect our expectations, are not guarantees of performance and speak only as of the dates the statements are made. Except as required by law, we do not undertake to update such forward-looking statements. You should not rely unduly on forward-looking statements.
Risk Factors
Our business results are subject to a variety of risks, including those that are described below and elsewhere in our filings with the
SEC. The risks described below are not the only risks we face. Additional risks not currently known to us or that we currently deem to be immaterial may also significantly adversely affect our business. If any of these risks were to materialize or intensify, our expectations (or the underlying assumptions) may change and our performance may be adversely affected.
STRATEGY AND BRAND
If we do not successfully evolve and execute against our business strategies, we may not be able to drive business growth.
To drive Systemwide sales, operating income and free cash flow growth, our business strategies – including the components of our Accelerating the Arches growth strategy – must be effective in maintaining and strengthening customer appeal and capturing additional market share. Whether these strategies are successful depends mainly on our System’s continued ability to:
•capitalize on our global scale, iconic brand and local market presence to build upon our historic strengths and competitive advantages, including by maximizing our marketing, committing to our core menu items, and doubling down on digital, delivery, drive thru and restaurant development;
•innovate and differentiate the McDonald’s experience, including by preparing and serving our food in a way that balances value and convenience to our customers with profitability;
•build upon our investments to transform and enhance the customer experience, including building one of the world’s largest consumer platforms to fuel engagement;
•run great restaurants by building the easiest and most efficient restaurant operating platform which enables franchisees to run restaurants more efficiently and utilize the latest cloud-based technology to make it easier for crews to deliver exceptional customer service;
•accelerate our existing strategies, including through growth opportunities and building a modern company platform that unlocks speed and innovation throughout the organization; and
•evolve and adjust our strategies in response to, among other things, changing consumer behavior, and other events impacting our results of operations and liquidity.
If we are delayed or unsuccessful in evolving or executing against our strategies, if the execution of our strategies proves to be more difficult, costly or time consuming than expected, or if our strategies do not yield the desired results, our business, financial condition and results of operations may suffer.
Failure to preserve the value or relevance of our brand could have an adverse impact on our financial results.
To continue to be successful in the future, we believe we must preserve, enhance and leverage the value and relevance of our brand, including our corporate purpose, mission and values. Brand value is based in part on consumer perceptions, which are affected by a variety of factors, including the nutritional content and preparation of our food, the ingredients we use, the manner in which we source commodities and general business practices across the System, including the people practices at McDonald’s restaurants. Consumer acceptance of our offerings is subject to change for a variety of reasons, and some changes can occur rapidly. For example, nutritional, health, environmental and other scientific studies and conclusions, which continuously evolve and may have contradictory implications, drive popular opinion, litigation and regulation (including initiatives intended to drive consumer behavior) in ways that affect the “informal eating out” (“IEO”) segment or perceptions of our brand, generally or relative to available alternatives. Our business could also be impacted by business incidents or practices, whether actual or perceived, particularly if they receive considerable publicity or result in litigation or governmental investigations or proceedings, as well as by our perceived position or lack of position on environmental, social responsibility, public policy, geopolitical and similar matters. In addition, we cannot ensure that franchisees or business partners will not take actions that adversely affect the value and relevance of our brand. Consumer perceptions may also be affected by adverse commentary from third parties, including through social media or conventional media outlets, regarding the quick-service category of the IEO segment or our brand, culture, operations, suppliers or franchisees. If we are unsuccessful in addressing adverse commentary or perceptions, whether or not accurate, our brand and financial results may suffer.
If we do not anticipate and address industry trends and evolving consumer preferences and effectively execute our pricing, promotional and marketing plans, our business could suffer.
Our continued success depends on our System’s ability to build upon our historic strengths and competitive advantages. In order to do so, we need to anticipate and respond effectively to continuously shifting consumer demographics and industry trends in food sourcing, food preparation, food offerings, and consumer behavior and preferences, including with respect to the use of digital channels and environmental and social responsibility matters. If we are not able to predict, or quickly and effectively respond to, these changes, or if our competitors are
McDonald's Corporation 2024 Annual Report 28



able to do so more effectively, our financial results could be adversely impacted.
Our ability to build upon our strengths and advantages also depends on the impact of pricing, promotional and marketing plans across the System, and the ability to adjust these plans to respond quickly and effectively to evolving customer behavior and preferences, as well as shifting economic and competitive conditions. Existing or future pricing strategies and marketing plans, as well as the value proposition they represent, are expected to continue to be important components of our business strategy. However, they may not be successful, or may not be as successful as the efforts of our competitors, which could negatively impact sales, guest counts and market share.
Additionally, we operate in a complex and costly advertising environment. Our marketing and advertising programs may not be successful in reaching consumers in the way we intend. Our success depends in part on whether the allocation of our advertising and marketing resources across different channels, including digital, allows us to reach consumers effectively, efficiently and in ways that are meaningful to them. If our advertising and marketing programs are not successful, or are not as successful as those of our competitors, our sales, guest counts and market share could decrease.
Our investments to transform and enhance the customer experience, including through technology, may not generate the expected results.
Our long-term business objectives depend on the successful Systemwide execution of our strategies. We continue to build upon our investments in restaurant development, technology, digital engagement and delivery in order to transform and enhance the customer experience. As part of these investments, we are continuing to place emphasis on improving our service model and strengthening relationships with customers, in part through digital channels and loyalty initiatives, mobile ordering and payment systems, and enhancing our drive thru technologies, which efforts may not generate expected results. We also continue to expand and refine our delivery initiatives, including through integrating delivery and mobile ordering. Utilizing a third-party delivery service may not have the same level of profitability as a non-delivery transaction and may introduce additional food quality, food safety and customer satisfaction risks. If these customer experience initiatives are not successfully executed, or if we do not fully realize the intended benefits of these significant investments, our business results may suffer.
We face intense competition in our markets, which could hurt our business.
We compete primarily in the IEO segment, which is highly competitive. We also face sustained, intense competition from traditional, fast casual and other competitors, which may include many non-traditional market participants such as convenience stores, grocery stores, coffee shops and online retailers. We expect our environment to continue to be highly competitive and our results in any particular reporting period may be impacted by a contracting IEO segment or by new or continuing actions, product offerings, technologies or consolidation of our competitors and third-party partners, which may have short- and long-term impacts on our results.
We compete primarily on the basis of product choice, quality, affordability, service and location. In particular, we believe our ability to compete successfully in the current market environment depends on our ability to improve existing products, successfully develop and introduce new products, price our products appropriately, deliver a relevant customer experience, manage the complexity of our restaurant operations, manage our investments in restaurant development, technology, digital engagement and delivery, and respond effectively to our competitors’ actions or offerings or to unforeseen disruptive actions. There can be no assurance these strategies will be effective, and some strategies may be effective at improving some metrics while adversely affecting others, which could have the overall effect of harming our business.
We may not be able to adequately protect our intellectual property or adequately ensure that we are not infringing the intellectual property of others, which could harm the value of the McDonald’s brand and our business.
Our success depends on our continued ability to use our existing trademarks and service marks in order to increase brand awareness and further develop our branded products in both domestic and international markets. We rely on a combination of trademarks, copyrights, service marks, trade secrets, patents and other intellectual property rights to protect our brand and branded products.
We have registered certain trademarks and have other trademark registrations pending in the U.S. and certain foreign jurisdictions. The trademarks that we currently use have not been, and may never be, registered in all of the countries outside of the U.S. in which we do business or may do business in the future. It may be costly and time consuming to protect our intellectual property, particularly in rapidly evolving areas, and the steps we have taken to do so in the U.S. and foreign countries may not be adequate. In addition, the steps we have taken may not adequately ensure that we do not infringe the intellectual property of others, and third parties may claim infringement by us in the future. In particular, we may be involved in intellectual property claims, including often aggressive or opportunistic attempts to enforce patents used in information technology systems, which might affect our operations and results. Any claim of infringement, whether or not it has merit, could, particularly in rapidly evolving areas, be time consuming, or result in costly litigation and could also have an adverse impact on our business.
In addition, we cannot ensure that franchisees and other third parties who hold licenses to our intellectual property will not take actions that adversely affect the value of our intellectual property.
OPERATIONS
The global scope of our business subjects us to risks that could negatively affect our business.
We encounter differing and evolving cultural, regulatory, geopolitical and economic environments within and among the more than 100 countries where McDonald’s restaurants operate, and our ability to achieve our business objectives depends on the System’s success in these environments. Meeting customer expectations is complicated by the risks inherent in our global operating environment, and our global success is partially dependent on our System’s ability to leverage operating successes across markets and brand perceptions. Planned initiatives may not have appeal across multiple markets with McDonald’s customers and could drive unanticipated changes in customer perceptions and negatively impact our business results.
Disruptions in operations or price volatility in a market can also result from governmental actions (whether proposed or realized, unilateral or bilateral), such as price, foreign exchange or trade-related tariffs or controls, trade policies and regulations, sanctions and counter sanctions, government-mandated closure of our, our franchisees’ or our suppliers’ operations, and asset seizures. Such disruptions
McDonald's Corporation 2024 Annual Report 29



or volatility can also result from acts of war, terrorism or other hostilities. The broader impact of acts of war and related sanctions, including on macroeconomic conditions, geopolitical tensions, consumer demand and the ability of us and our franchisees to operate in certain geographic areas, may also have an adverse impact on our business and financial results.
While we may face challenges and uncertainties in any of the markets in which we operate, such challenges and uncertainties are often heightened in developing markets, which may entail a relatively higher risk of political instability, economic volatility, crime, corruption and social and ethnic unrest. In many cases, such challenges may be exacerbated by the lack of an independent and experienced judiciary and uncertainty in how local law is applied and enforced, including in areas most relevant to commercial transactions and foreign investment. An inability to manage effectively the risks associated with our international operations could adversely affect our business and financial results.
Supply chain interruptions may increase costs or reduce revenues.
We depend on the effectiveness of our supply chain management to assure a reliable and sufficient supply of quality products, equipment and other materials on favorable terms. Although many of these items are sourced from a wide variety of suppliers in countries around the world, certain items have limited suppliers, which increases our reliance on those suppliers. Supply chain interruptions and related price increases have in the past and may in the future adversely affect us as well as our suppliers and franchisees, whose performance may have a significant impact on our results. Such interruptions and price increases could be caused by shortages, inflationary pressures, unexpected increases in demand, transportation-related issues, labor-related issues, technology-related issues, weather-related events, natural disasters, acts of war, terrorism or other hostilities, or other factors beyond our control or that of our suppliers or franchisees. Interruptions in our System’s supply chain or ineffective contingency planning can increase our costs, impact ingredient quality, delay new restaurant openings, and/or limit the quality or availability of products, equipment and other materials that are critical to our System’s operations or to restaurant development.
Our franchise business model presents a number of risks.
Our success as a heavily franchised business relies to a large degree on the financial success and cooperation of our franchisees, including our developmental licensees and affiliates. Our restaurant margins arise from two sources: fees from franchised restaurants (e.g., rent and royalties based on a percentage of sales) and, to a lesser degree, sales from Company-owned and operated restaurants. Our franchisees manage their businesses independently and therefore are responsible for the day-to-day operation of their restaurants. The revenues we realize from franchised restaurants are largely dependent on the ability of our franchisees to grow their sales. Business risks affecting our operations also affect our franchisees. If franchisee sales trends worsen, or any of such risks materialize or intensify, our financial results could be negatively affected, which may be material.
Our success also relies on the willingness and ability of our franchisees and affiliates to implement major initiatives, which may include financial investment, and to remain aligned with us on operating, value/promotional and capital-intensive reinvestment plans. The ability of franchisees to contribute to the achievement of our plans is dependent in large part on the availability to them of funding at reasonable interest rates and may be negatively impacted by the financial markets in general, by their or our creditworthiness or by banks’ lending practices. If our franchisees are unwilling or unable to invest in major initiatives or are unable to obtain financing at commercially reasonable rates, or at all, our future growth and results of operations could be adversely affected.
Our operating performance could also be negatively affected if our franchisees experience food safety or other operational problems or project an image inconsistent with our brand and values, particularly if our contractual and other rights and remedies are limited, costly to exercise or subjected to litigation and potential delays. If franchisees do not successfully operate restaurants in a manner consistent with our required standards, our brand’s image and reputation could be harmed, which in turn could hurt our business and operating results.
Our ownership mix also affects our results and financial condition. The decision to own restaurants or to operate under franchise or license agreements is driven by many factors whose interrelationship is complex. The benefits of our more heavily franchised structure depend on various factors, including whether we have effectively selected franchisees, licensees and/or affiliates that meet our rigorous standards, whether we are able to successfully integrate them into our structure and whether their performance and the resulting ownership mix supports our brand and financial objectives.
Continued challenges with respect to labor, including availability and cost, could adversely impact our business and results of operations.
Our success depends in part on our System’s ability to effectively attract, recruit, develop, motivate and retain qualified individuals to work in McDonald’s restaurants and to maintain appropriately-staffed restaurants in an intensely competitive labor market. We and our franchisees have experienced and may continue to experience challenges in adequately staffing certain McDonald’s restaurants, which can negatively impact operations, including speed of service to customers, and customer satisfaction levels. The System’s ability to meet its labor needs as they evolve is generally subject to a variety of factors, including the availability of sufficient workforce, unemployment levels and prevailing wages in the markets in which we operate.
Further, our System has experienced increased costs and competition associated with attracting, recruiting, developing, motivating and retaining qualified employees, as well as with promoting awareness of the opportunities of working at McDonald’s restaurants. We and our franchisees also continue to be impacted by increasingly complex U.S. and international laws and regulations affecting our respective workforces. These laws and regulations are increasingly focused on, and in certain cases impose requirements with respect to, employment matters such as wages and hours, healthcare, immigration, retirement and other employee benefits and workplace practices. Such laws and regulations can expose us and our franchisees to increased costs and other effects of compliance, including potential liability, and all such labor and compliance costs could have a negative impact on our Company-owned and operated margins and franchisee profitability.
Our potential exposure to reputational and other harm regarding our workplace practices or conditions or those of our independent franchisees or suppliers, including those giving rise to claims of harassment or discrimination (or perceptions thereof) or workplace safety, could have a negative impact on consumer perceptions of us and our business. Additionally, economic action, such as boycotts, protests, work stoppages or campaigns by labor organizations, could adversely affect us (including our ability to attract, recruit, develop, motivate and retain talent) or our franchisees and suppliers, whose performance may have a significant impact on our results.
McDonald's Corporation 2024 Annual Report 30



Effective succession planning is important to our continued success.
Effective succession planning for management is important to our long-term success. Failure to effectively attract, recruit, develop, motivate and retain qualified key personnel, or to execute smooth personnel transitions, could disrupt our business and adversely affect our results.
Food safety concerns may have an adverse effect on our business.
Food safety concerns have had and may in the future have an adverse effect on our business. Our ability to increase sales and profits depends on our System’s ability to meet expectations for safe food and on our ability to manage the potential impact on McDonald’s of food-borne illnesses and food or product safety issues that may arise in the future, including in the supply chain, restaurants or delivery. Food safety is a top priority, and we dedicate substantial resources aimed at ensuring that our customers enjoy safe food products, including as our menu and service model evolve. However, food safety events, including instances of food-borne illness, have occurred within the food industry and our System from time to time (including the E. coli event in the U.S. in October 2024) and could occur in the future. Instances of food tampering, food contamination or food-borne illness, whether actual or perceived, could adversely affect our brand, reputation and financial results.
If we do not effectively manage our real estate portfolio, our operating results may be negatively impacted.
We have significant real estate operations, primarily in connection with our restaurant business. We generally own or secure a long-term lease on the land and building for conventional franchised and Company-owned and operated restaurant sites. We seek to identify and develop restaurant locations that offer convenience to customers and long-term sales and profit potential. As we generally secure long-term real estate interests for our restaurants, we have limited flexibility to quickly alter our real estate portfolio. The competitive business landscape continues to evolve in light of changing business trends, consumer preferences, trade area demographics, consumer use of digital, delivery and drive thru, local competitive positions and other economic factors. If our restaurants are not located in desirable locations, or if we do not evolve in response to these factors, it could adversely affect Systemwide sales and profitability.
Our real estate values and the costs associated with our real estate operations are also impacted by a variety of other factors, including governmental regulations, insurance, zoning, tax and eminent domain laws, interest rate levels, the cost of financing, natural disasters, acts of war, terrorism or other hostilities, or other factors beyond our control. A significant change in real estate values, or an increase in costs as a result of any of these factors, could adversely affect our operating results.
Information technology system failures or interruptions, or breaches of network security, may impact our operations or cause reputational harm.
We are increasingly reliant upon technology systems, such as point-of-sale, that support our business operations, including our digital and delivery solutions, and technologies that facilitate communication and collaboration with affiliated entities, customers, employees, franchisees, suppliers, service providers or other independent third parties to conduct our business, whether developed and maintained by us or provided by third parties. Any failure or interruption of these systems could significantly impact our or our franchisees’ operations, or our customers’ experiences and perceptions. In addition, the artificial intelligence tools we are incorporating into certain aspects of our business may not generate the intended efficiencies and may impact our business results.
Security incidents and breaches have from time to time occurred and may in the future occur involving our systems, the systems of the parties with whom we communicate or collaborate (including franchisees) or the systems of third-party providers. These may include such things as unauthorized access, phishing attacks, account takeovers, denial of service, computer viruses, deepfakes and other malicious uses of artificial intelligence, introduction of malware or ransomware, other disruptive problems caused by hackers or unintentional events. Certain of these technology systems contain personal, confidential, financial and other information of our customers, employees, franchisees and their employees, suppliers and other third parties, as well as financial, proprietary and other confidential information related to our business. Despite response procedures and measures in place in the event an incident occurs, it could result in disruptions, shutdowns, or a security breach including the theft or unauthorized disclosure of certain of the above-described information. The actual or alleged occurrence of any of these types of incidents could result in mitigation costs, reputational damage, adverse publicity, loss of consumer confidence, reduced sales and profits, complications in executing our growth initiatives and regulatory and legal risk, including administrative fines, criminal or civil penalties or civil liabilities.
Despite the implementation of business continuity measures, any of these technology systems could become vulnerable to damage, disability or failures due to fire, power loss, telecommunications failure or other catastrophic events. Certain technology systems may also become vulnerable, unreliable or inefficient in cases where technology vendors limit or terminate product support and/or maintenance. Our increasing reliance on third-party systems also subjects us to risks faced by those third-party businesses, including operational, security and credit risks. Further, the technology systems of third parties upon which we rely to conduct our business could be compromised in a manner that adversely affects us and our technology systems, information and business continuity. If technology systems were to fail or otherwise be unavailable, or if business continuity or disaster recovery plans were not effective, and we were unable to recover in a timely manner, we could experience an interruption in our or our franchisees’ operations. While we maintain insurance coverage designed to address certain aspects of cybersecurity risks, such insurance coverage may be insufficient to cover all losses or all types of claims that may arise.
LEGAL AND REGULATORY
Increasing regulatory and legal complexity may adversely affect our business and financial results.
Our regulatory and legal environment worldwide exposes us to complex compliance, litigation and similar risks that could affect our operations and results in material ways. Many of our markets are subject to increasing, conflicting and highly prescriptive regulations involving, among other matters, restaurant operations, product packaging, marketing, use of information technology systems, the nutritional and allergen content and safety of our food and other products, labeling and other disclosure practices. Compliance efforts with those regulations may be affected by ordinary variations in food preparation among our own restaurants and the need to rely on the accuracy and completeness of information from third-party suppliers. We also are subject to increasing public focus, including by governmental and non-governmental organizations, on environmental, social responsibility and corporate governance matters. Our success depends in part on our
McDonald's Corporation 2024 Annual Report 31



ability to manage the impact of regulations and other initiatives that can affect our business plans and operations, which have increased and may continue to increase our costs of doing business and exposure to litigation, governmental investigations or other proceedings.
We are also subject to legal proceedings that may adversely affect our business, including, but not limited to, class actions, administrative proceedings, government investigations and proceedings, shareholder proceedings, employment and personal injury claims, landlord/tenant disputes, supplier-related disputes, and claims by current or former franchisees. Regardless of whether claims against us are valid or whether we are found to be liable, claims may be expensive to defend and may divert management’s attention away from operations.
Litigation, legislative and regulatory action concerning our relationship with franchisees and the legal distinction between our franchisees and us for employment law or other purposes, if determined adversely, could challenge our franchise business model, increase costs, negatively impact our business operations and the business prospects of our franchisees and subject us to incremental liability for their actions. Similarly, although our commercial relationships with our suppliers remain independent, there may be attempts to challenge that independence, which, if determined adversely, could also increase costs, negatively impact the business prospects of our suppliers, and subject us to incremental liability for their actions.
Our results could also be affected by the following:
•the relative level of our defense costs, which vary from period to period depending on the number, nature and procedural status of pending proceedings;
•the cost and other effects of settlements, judgments or consent decrees, which may require us to make disclosures or take other actions that may affect perceptions of our brand and products; and
•adverse results of pending or future litigation, including litigation challenging the composition and preparation of our products, or the appropriateness or accuracy of our marketing or other communication practices.
A judgment significantly in excess of any applicable insurance coverage or third-party indemnity could materially adversely affect our financial condition or results of operations. Further, adverse publicity resulting from claims may hurt our business. If we are unable to effectively manage the risks associated with our complex regulatory and legal environment, it could have a material adverse effect on our business and financial condition.
Changes in tax laws and unanticipated tax liabilities could adversely affect the taxes we pay and our profitability.
We are subject to income and other taxes in the U.S. and foreign jurisdictions, and our operations, plans and results are affected by tax and other initiatives around the world. In particular, we are affected by the impact of changes to tax laws or policy or related authoritative interpretations. We are also impacted by settlements of pending or any future adjustments proposed by taxing and governmental authorities inside and outside of the U.S. in connection with our tax audits, all of which will depend on their timing, nature and scope. Any significant increases in income tax rates, changes in income tax laws or unfavorable resolution of tax matters could have a material adverse impact on our financial results.
Changes in accounting standards or the recognition of impairment or other charges may adversely affect our future operations and results.
New accounting standards or changes in financial reporting requirements, accounting principles or practices, including with respect to our critical accounting estimates, could adversely affect our future results. We may also be affected by the nature and timing of decisions about underperforming markets or assets, including decisions that result in impairment or other charges that reduce our earnings.
In assessing the recoverability of our long-lived assets, we consider changes in economic conditions and make assumptions regarding estimated future cash flows and other factors. These estimates are highly subjective and can be significantly impacted by many factors such as global and local business and economic conditions, operating costs, inflation, interest rate levels, competition, consumer and demographic trends and our restructuring activities. If our estimates or underlying assumptions change in the future, we may be required to record impairment charges. Any such changes could have a significant adverse effect on our reported results for the affected periods.
If we fail to comply with privacy and data protection laws, we could be subject to legal proceedings and penalties, which could negatively affect our financial results or brand perceptions.
We are subject to legal and compliance risks and associated liability related to privacy and data protection requirements, including those associated with our technology-related services and platforms made available to business partners, customers, employees, franchisees or other third parties. An increasing number of our markets have enacted new privacy and data protection requirements (including the European Union’s General Data Protection Regulation and various U.S. state-level laws), and further requirements are likely to be proposed or enacted in the future. Failure to comply with these privacy and data protection laws could result in legal proceedings and substantial administrative fines, criminal or civil penalties or civil liabilities and materially adversely impact our financial results or brand perceptions.
MACROECONOMIC AND MARKET CONDITIONS
Unfavorable general economic conditions could adversely affect our business and financial results.
Our results of operations are substantially affected by economic conditions, including inflationary pressures, which can vary significantly by market and can impact consumer disposable income levels and spending habits. Economic conditions can be impacted by a variety of factors, including hostilities, epidemics, pandemics and actions taken by governments to manage national and international economic matters, whether through austerity, stimulus measures or trade measures, and initiatives intended to control wages, unemployment, credit availability, inflation, taxation and other economic drivers. Sustained adverse economic conditions or periodic adverse changes in economic conditions put pressure on our operating performance and business continuity disruption planning, and our business and financial results may suffer as a result.
Our results of operations are also affected by fluctuations in currency exchange rates, and unfavorable currency fluctuations could adversely affect reported earnings.
McDonald's Corporation 2024 Annual Report 32



Health epidemics or pandemics could adversely affect our business and financial results.
Health epidemics or pandemics have in the past and may in the future impact macroeconomic conditions, consumer behavior, labor availability and supply chain management, as well as local operations in impacted markets, all of which can adversely affect our business, financial results and outlook. Governmental responses to health epidemics or pandemics, including operational restrictions and temporary restaurant closures, can also affect the foregoing items and adversely affect our business and financial results. The duration and scope of a health epidemic or pandemic can be difficult to predict and depends on many factors, including the emergence of new variants and the availability, acceptance and effectiveness of preventative measures. A health epidemic or pandemic may also heighten other risks disclosed in these Risk Factors, including, but not limited to, those related to the availability and costs of labor and commodities, supply chain interruptions, consumer behavior, and consumer perceptions of our brand and industry.
Changes in commodity and other operating costs could adversely affect our results of operations.
The profitability of our Company-owned and operated restaurants depends in part on our ability to anticipate and react to changes in commodity costs, including food, paper, supplies, fuel and utilities, as well as distribution and other operating costs, including labor. Volatility in certain commodity prices and fluctuations in labor costs have adversely affected and in the future could adversely affect our operating results by impacting restaurant profitability. The commodity markets for some of the ingredients we use, such as beef and chicken, are particularly volatile due to factors such as seasonal shifts, climate conditions, industry demand and other macroeconomic conditions, international commodity markets, food safety concerns, product recalls, government regulation, and acts of war, terrorism or other hostilities, all of which are beyond our control and, in many instances, unpredictable. Our System can only partially address future price risk through hedging and other activities, and therefore increases in commodity costs could have an adverse impact on our profitability.
A decrease in our credit ratings or an increase in our funding costs could adversely affect our profitability.
Our credit ratings may be negatively affected by our results of operations or changes in our debt levels. As a result, our interest expense, the availability of acceptable counterparties, our ability to obtain funding on favorable terms, our collateral requirements and our operating or financial flexibility could all be negatively affected, especially if lenders were to impose new operating or financial covenants.
Our operations may also be impacted by regulations affecting capital flows, financial markets or financial institutions, which can limit our ability to manage and deploy our liquidity or increase our funding costs. Any such events could have a material adverse effect on our business and financial condition.
The trading volatility and price of our common stock may be adversely affected by many factors.
Many factors affect the trading volatility and price of our common stock in addition to our operating results and prospects. These factors, many of which are beyond our control, include the following:
•the unpredictable nature of global economic and market conditions;
•governmental action or inaction in light of key indicators of economic activity or events that can significantly influence financial markets, particularly in the U.S., which is the principal trading market for our common stock, and media reports and commentary about economic, trade or other matters, even when the matter in question does not directly relate to our business;
•trading activity in our common stock, in derivative instruments with respect to our common stock or in our debt securities, which can be affected by: market commentary (including commentary that may be unreliable or incomplete); unauthorized disclosures about our performance, plans or expectations about our business; our actual performance and creditworthiness; investor confidence, driven in part by expectations about our performance; actions by shareholders and others seeking to influence our business strategies; portfolio transactions in our common stock by significant shareholders; and trading activity that results from the ordinary course rebalancing of stock indices in which McDonald’s may be included, such as the S&P 500 Index and the Dow Jones Industrial Average;
•the impact of our stock repurchase program or dividend rate; and
•the impact of corporate actions, including changes to our corporate structure, and market and third-party perceptions and assessments of such actions, including those we may take from time to time as we implement our business strategies in light of changing business, legal and tax considerations.
Our business is subject to an increasing focus on environmental and social impact matters.
In recent years, there has been an increasing focus by stakeholders – including employees, franchisees, customers, suppliers, governmental and non-governmental organizations and investors – on environmental and social impact matters. A failure, whether real or perceived, to address environmental and social impact matters or to achieve progress on our environmental and social impact initiatives on the anticipated timing or at all, could adversely affect our business, including by heightening other risks disclosed in these Risk Factors, such as those related to consumer behavior, consumer perceptions of our brand, labor availability and costs, supply chain interruptions, commodity costs, and legal and regulatory complexity. Conversely, our taking a position, whether real or perceived, on environmental and social impact, public policy, geopolitical and similar matters could also adversely impact our business.
The standards we set for ourselves regarding environmental and social impact matters, and our ability to meet such standards, may also impact our business. For example, we are working to manage risks and costs to our System related to climate change, greenhouse gases, and diminishing energy and water resources, and we have announced initiatives relating to, among other things, climate action, sustainability, and responsible sourcing. In addition, we are engaging in social impact initiatives, including community engagement and philanthropy; as well as our commitment to inclusion. We have faced increased scrutiny related to reporting on and achieving these initiatives, as well as continued public focus on similar matters, such as packaging and waste, animal health and welfare, deforestation and land use. We have also experienced increased pressure from stakeholders to provide expanded disclosure and establish additional commitments, targets or goals, and take actions to meet them, which could expose us to additional market, operational, execution and reputational costs and risks. Moreover, addressing environmental and social impact matters requires Systemwide as well as third party
McDonald's Corporation 2024 Annual Report 33



coordination and alignment, over which we do not have complete control and which may be unpredictable. The standards by which certain environmental and social impact matters are measured are also evolving and subject to assumptions that could change over time.
Events such as severe weather conditions, natural disasters, hostilities, social and geopolitical unrest and climate change, among others, can adversely affect our results and prospects.
Severe weather conditions, natural disasters, acts of war, terrorism or other hostilities, social and geopolitical unrest or climate change (or expectations about them) can adversely affect consumer behavior and confidence levels, supply availability and costs and local operations, including temporary restaurant closures and delayed new restaurant openings, in impacted markets, all of which can affect our results and prospects. Climate change may also increase the frequency and severity of weather-related events and natural disasters. Our receipt of proceeds under any insurance we maintain with respect to some of these risks may be delayed or the proceeds may be insufficient to cover our losses fully.

McDonald's Corporation 2024 Annual Report 34
"""

item1b_text = """MANAGEMENT'S DISCUSSION AND ANALYSIS OF FINANCIAL CONDITION AND RESULTS OF OPERATIONS
 
MANAGEMENT'S VIEW OF THE BUSINESS
In analyzing business trends, management reviews results on a constant currency basis and considers a variety of performance and financial measures, some of which are considered to be non-GAAP, including comparable sales and guest count growth, Systemwide sales growth, after-tax return on invested capital from continuing operations, free cash flow and free cash flow conversion rate, as described below. Management believes these measures are important in understanding the financial performance of the Company.
•Constant currency results exclude the effects of foreign currency translation and are calculated by translating current year results at prior year average exchange rates. Management reviews and analyzes business results excluding the effect of foreign currency translation, impairment and other charges and gains, as well as material regulatory and other income tax impacts, and bases incentive compensation plans on these results because the Company believes this better represents underlying business trends.
•Comparable sales and comparable guest counts are compared to the same period in the prior year and represent sales and transactions, respectively, at all restaurants, whether owned and operated by the Company or by franchisees, in operation at least thirteen months including those temporarily closed. Some of the reasons restaurants may be temporarily closed include reimaging or remodeling, rebuilding, road construction, natural disasters, pandemics and acts of war, terrorism or other hostilities. Restaurants in Russia were treated as permanently closed as of April 1, 2022 and therefore excluded from the calculation of comparable sales and comparable guest counts beginning in the second quarter of 2022. Comparable sales exclude the impact of currency translation and the sales of any market considered hyperinflationary (generally identified as those markets whose cumulative inflation rate over a three-year period exceeds 100%), which management believes more accurately reflects the underlying business trends. Beginning in the first quarter of 2023, McDonald's excluded results from Argentina and Lebanon in the calculation of comparable sales due to hyperinflation (Venezuela continues to be excluded). Comparable sales are driven by changes in guest counts and average check, the latter of which is affected by changes in pricing and product mix.
•Systemwide sales include sales at all restaurants, whether owned and operated by the Company or by franchisees. Systemwide sales to loyalty members is comprised of all sales to customers who self-identify as a loyalty member when transacting with both Company-owned and operated and franchised restaurants. Systemwide sales to loyalty members are measured across 60 markets with loyalty programs. Systemwide sales to loyalty members represents an aggregation of the prior four quarters of sales to loyalty members active in the last 90 days of the respective quarter. While franchised sales are not recorded as revenues by the Company, management believes the information is important in understanding the Company's financial performance because these sales are the basis on which the Company calculates and records franchised revenues and are indicative of the financial health of the franchisee base. The Company's revenues consist of sales by Company-owned and operated restaurants and fees from franchised restaurants operated by conventional franchisees, developmental licensees and affiliates. Changes in Systemwide sales are primarily driven by comparable sales and net restaurant unit expansion.
•The Company’s after-tax return on invested capital ("ROIC") from continuing operations is a metric that management believes measures capital-allocation effectiveness over time. Other companies may calculate ROIC differently, limiting the usefulness of the measure for comparisons with other companies. Refer to the reconciliation in Exhibit 99.1 to this Form 10-K for further information on the Company's calculation of ROIC.
•Free cash flow, defined as cash provided by operations less capital expenditures, and free cash flow conversion rate, defined as free cash flow divided by net income, are measures reviewed by management in order to evaluate the Company’s ability to convert net profits into cash resources, after reinvesting in the core business, that can be used to pursue opportunities to enhance shareholder value. Refer to the reconciliations in Exhibit 99.1 to this Form 10-K for further information on the Company's calculations of free cash flow and free cash flow conversion rate.
McDonald's Corporation 2024 Annual Report 7



2024 FINANCIAL PERFORMANCE
In 2024, global comparable sales decreased 0.1%.
•Comparable sales in the U.S. increased 0.2%, benefiting from average check growth, partly offset by negative comparable guest counts.
•Comparable sales in the International Operated Markets segment decreased 0.2%, reflecting mixed results across the markets. Negative comparable sales across some markets, led by France, was partly offset by positive comparable sales in most markets.
•Comparable sales in the International Developmental Licensed Markets segment decreased 0.3%. The continued impact of the war in the Middle East and negative comparable sales in China more than offset positive comparable sales in Latin America and Japan.
Earnings and cash flow growth rates presented below were impacted in 2024 by restructuring charges associated with Accelerating the Organization and net charges primarily consisting of transaction costs, property sale gains and non-cash impairment charges associated with the sale of McDonald's business in South Korea and transaction costs associated with the acquisition of McDonald's business in Israel. Additionally, 2023 results were impacted by charges related to the Company's Accelerating the Arches growth strategy, including restructuring charges associated with Accelerating the Organization, and charges related to the write-off of impaired software no longer in use.
Current year and prior year charges and gains are detailed along with reconciliations to the non-GAAP measures in the Net Income and Diluted Earnings Per Share section on page 13 and Operating Income section on page 18 in this Form 10-K.
In addition to the comparable sales results above, the Company had the following financial results in 2024:
•Consolidated revenues increased 2% (2% in constant currencies) to $25.9 billion.
•Systemwide sales increased 1% (2% in constant currencies) to $130.7 billion.
•Consolidated operating income increased 1% (1% in constant currencies) to $11.7 billion.
•Operating margin, defined as operating income as a percent of total revenues, decreased from 46% in 2023 to 45% in 2024.
•Diluted earnings per share of $11.39 decreased 1% (1% in constant currencies).
•Cash provided by operations was $9.4 billion, a 2% decrease from the prior year.
•Capital expenditures of $2.8 billion were mainly allocated to new restaurant openings and, to a lesser extent, to reinvestment in existing restaurants.
•Free cash flow was $6.7 billion, an 8% decrease from the prior year.
•Across the System, over 2,100 new restaurants (including those in our developmental licensee and affiliated markets) were opened.
•The Company increased its quarterly cash dividend per share by 6% to $1.77 for the fourth quarter, equivalent to an annual dividend of $7.08 per share. The Company returned a total of $7.7 billion to shareholders through dividends and share repurchases in 2024.

McDonald's Corporation 2024 Annual Report 8



STRATEGIC DIRECTION
The Company’s Accelerating the Arches growth strategy (the “Strategy”) encompasses all aspects of McDonald’s business as the leading global omni-channel restaurant brand. Our Strategy reflects the Company’s purpose, mission and values, as well as growth pillars that build on the Company’s competitive advantages. The Company's guiding purpose, mission and values are discussed in a dedicated section on page 4 of this Form 10-K.

GROWTH PILLARS
The following growth pillars, M-C-D, build on historic strengths and articulate areas of further opportunity. Under our Strategy, the Company will:
•Maximize our Marketing by investing in new, culturally relevant approaches, grounded in fan truths, to effectively communicate the story of our brand, food and purpose. The Company continues to build relevance with customers through emotional connections and world class creative, which are central to the brand’s “Feel-Good Marketing” approach. This is exemplified by campaigns that elevate the entire brand and continue to be scaled around the globe to connect with customers in authentic and relatable ways. The Company is committed to a marketing strategy that highlights value at every tier of the menu, as providing delicious and affordable menu options remains a cornerstone of the McDonald’s brand. This includes everyday low-price options on our menu, affordable meal bundles, limited-time deals and personalized value and digital offers available in our mobile app.

•Commit to the Core menu by tapping into customer demand for the familiar and focusing on serving our iconic products that are beloved by customers around the world such as our World Famous Fries, Big Mac, Quarter Pounder and Chicken McNuggets, which are some of our seventeen unique billion-dollar brands. Building on its foundational strength with burgers, the Company will continue to evolve and innovate its longest-standing menu item with plans to implement “Best Burger”; a series of operational and formulation changes designed to deliver hotter, juicier, tastier burgers to nearly all markets by the end of 2026. Further, the Company is focused on continuing to gain share in the rapidly growing chicken category, as we continue to aggressively grow our chicken brands. This includes plans to offer the McCrispy sandwich in nearly all markets by the end of 2025 and to extend the McCrispy brand into strips and wraps in several markets. These planned innovations and new menu offerings reflect the Company’s ability to meet evolving customer preferences. The Company also continues to see a significant opportunity with beverages, such as coffee, demonstrated by markets leveraging the McCafé brand, customer experience, value and quality to drive long-term growth.

•Double Down on the 4D's: Digital, Delivery, Drive Thru and Restaurant Development by continuing to leverage competitive strengths and building a powerful digital experience growth engine to deliver a personalized and convenient customer experience. As another way to unlock further growth, the Company plans to continue to accelerate the pace of restaurant openings and technology innovation so that whenever and however customers choose to interact with McDonald’s, they can enjoy a fast, easy experience that meets their needs.
◦Digital: The Company’s digital experience is transforming how customers order, pay and receive their food. Through digital tools, customers can access personalized offers, participate in a loyalty program, order through our mobile app and receive McDonald's food through the channel of their choice. In the U.S., we are providing increased convenience to customers through “Ready on Arrival”; a digital enhancement that enables crew to begin assembling a customer’s mobile order prior to arrival at the restaurant to expedite service and elevate customer satisfaction. The Company plans to deploy this initiative in its top six markets by the end of 2025. The Company has successful loyalty programs in 60 markets, including its top six markets. McDonald’s loyalty customers have proven to be highly engaged, and the Company plans to increase its 90-day active users to 250 million by the end of 2027. Further, the Company plans to grow its annual Systemwide sales to loyalty members to $45.0 billion by the end of 2027.

◦Delivery: The Company offers delivery from over 38,000 restaurants across approximately 100 markets, representing nearly 90% of McDonald's restaurants. The Company is continuing to build on and enhance the delivery experience for customers, including adding the ability to place a delivery order in our mobile app (a feature that is currently available in five of the Company’s top markets). The Company continues to scale this capability and expects to increase the percentage of Systemwide delivery sales originating from our mobile app to 30% by the end of 2027. The Company also has long-term strategic partnerships with delivery providers that continue to benefit the Company, customers and franchisees by optimizing operational efficiencies and creating a seamless customer experience.

◦Drive Thru: The Company has the most drive thru locations worldwide, with nearly 28,000 drive thru locations globally, including over 95% of the over 13,500 locations in the U.S. This channel remains a competitive advantage in meeting customers’ demand for flexibility and choice. McDonald’s network currently provides unmatched scale and convenience for customers, while also offering significant growth opportunities, such as adding additional drive thru lanes to increase capacity and improve speed and efficiency. The Company continues to build on its drive thru advantage, as the vast majority of new restaurant openings in the U.S. and International Operated Markets will include a drive thru.

◦Restaurant Development: The Company will continue to accelerate the pace of restaurant openings to attempt to fully capture the demand being driven through our Strategy in many of our largest markets. In 2025, the Company plans to open about 2,200 new restaurants across the globe, which will contribute to slightly over 4% new unit growth (net of closures). Further, the Company continues to build on its industry-leading development, by progressing toward the targeted expansion to 50,000 restaurants by the end of 2027, which would make it the fastest period of restaurant unit growth in Company history.
McDonald's Corporation 2024 Annual Report 9



FOUNDATION AND PLATFORMS
Foundational to our Strategy is keeping the customer and restaurant crew at the center of everything the Company does, along with focusing relentlessly on running great restaurants, empowering our people and continuing to modernize our ways of working. Further, as part of the Company’s plans for long term growth and solidifying McDonald’s leadership position, the Company will continue to develop and implement three technology-enabled platforms designed to build our competitive advantages, cement our place in culture and stay one step ahead of our customers’ expectations. Together, our foundation and platforms will extend the Company’s leadership position and unlock new growth opportunities and efficiencies for our business over the long-term.
Our platforms are:
•Consumer: The Company is building one of the world’s largest consumer platforms to fuel engagement, which will bring together the best of our brand and utilize our physical and digital competitive advantages. The consumer platform will enable the Company to accelerate growth in our loyalty program and drive valuable loyalty customers to visit more frequently.
•Restaurant: The Company is building the easiest and most efficient restaurant operating platform which enables the Company and franchisees to run restaurants more efficiently and utilize the latest cloud-based technology to make it easier for restaurant crew to deliver exceptional customer service. The Company intends to deploy new, universal software that all McDonald’s restaurants will run on, enabling restaurants to roll out innovation even faster, with less complexity and more stability; and customers will enjoy a more familiar, consistent experience.
•Company: The Company is building a modern company platform, through our Global Business Services (GBS) organization, that unlocks speed and innovation throughout the organization, to enable further growth as it modernizes the way it works by focusing on becoming faster, more innovative and more efficient at solving problems for its customers and people.
Our Strategy is aligned with the Company’s capital allocation philosophy of: (i) invest in opportunities to grow the business and drive strong returns, including both capital expenditures as well as investments in technology, digital, and our GBS organization, (ii) prioritize our dividend and (iii) repurchase shares with remaining free cash flow over time.
The Company believes our Strategy builds on our inherent strengths by harnessing the Company’s competitive advantages while leveraging its size, scale, agility and the power of the McDonald’s brand to adapt and adjust to meet customer demands in varying economic environments, including the current industry-wide challenges associated with more discerning consumer spending. Our Strategy is supported by a strong global senior leadership team aimed at executing against the MCD growth pillars, further developing our three platforms and driving long-term growth through increasing guest counts and growing industry market share.

McDonald's Corporation 2024 Annual Report 10



OUTLOOK
2025 Outlook
Based on current conditions, the following is provided to assist in forecasting the Company's future results for 2025.
•The Company expects net restaurant unit expansion will contribute slightly over 2% to 2025 Systemwide sales growth, in constant currencies.
•The Company expects full year 2025 Selling, general and administrative expenses of about 2.2% of Systemwide sales.
•The Company expects 2025 operating margin percent to be in the mid-to-high 40% range.
•Based on current interest and foreign currency exchange rates, the Company expects interest expense for the full year 2025 to increase between 4% and 6% driven primarily by higher average debt balances and higher average interest rates.
•The Company expects the effective income tax rate for the full year 2025 to be between 20% and 22%. Some volatility may result in a quarterly tax rate outside of the annual range.
•The Company expects 2025 capital expenditures to be between $3.0 and $3.2 billion, with the majority directed towards new restaurant unit expansion across the U.S. and International Operated Markets. Globally, the Company expects to open approximately 2,200 restaurants. The Company expects to open about 600 restaurants in the U.S. and International Operated Markets segments, and that developmental licensees and affiliates will contribute capital towards about 1,600 restaurant openings in their respective markets. The Company expects nearly 1,800 net restaurant additions in 2025.
•The Company expects to achieve a free cash flow conversion rate in the low-to-mid 80% range.
Long-Term Outlook
Over the long-term, the Company expects to achieve the following average annual financial targets:
•Net restaurant unit expansion of about 2.5% of Systemwide sales growth, in constant currencies;
•Continued operating margin expansion;
•Sequential increases in capital expenditures of about $300 million to $500 million each year through 2027;
•Between 4% and 5% net new restaurant unit growth, targeting 50,000 global units by 2027 with a run rate of about 1,000 gross restaurant openings across the U.S. and International Operated Markets segments in 2027; and
•Free cash flow conversion rate targeted to be in the 90% range, with the conversion percentage likely below this target during a period of heightened investments.
McDonald's Corporation 2024 Annual Report 11



CONSOLIDATED OPERATING RESULTS
The following discussion should be read in conjunction with the consolidated financial statements and accompanying notes beginning on page 39 of this Form 10-K. This section generally discusses 2024 and 2023 items and the year-to-year comparisons between the years ended December 31, 2024 and 2023. Discussions of 2022 items and the year-to-year comparisons between the years ended December 31, 2023 and 2022 are not included in their entirety in this Form 10-K and can be found in the “Management’s Discussion and Analysis of Financial Condition and Results of Operations” section of the Company’s Annual Report on Form 10-K for the year ended December 31, 2023, filed with the SEC on February 22, 2024.
In the first quarter of 2024, the Company changed its rounding presentation to the nearest whole number in millions of reported amounts, except per share data or as otherwise designated. The change in rounding presentation has been applied to all prior year amounts presented. In certain circumstances, this change adjusted previously reported balances, however, these changes were not significant, and no other changes were made to previously reported financial information. Additionally, certain columns and rows in financial tables within management's discussion and analysis of financial condition and results of operations may not add due to rounding. Percentages have been calculated from the underlying whole-dollar amounts for all periods presented.
Impact of the War in the Middle East
The Company’s Systemwide sales and revenue have continued to be negatively impacted by the war in the Middle East, primarily in the International Developmental Licensed Markets & Corporate segment, where the majority of restaurants are under a developmental license or affiliate arrangement. The Company is monitoring the evolving situation, which it expects to continue to have a negative impact on Systemwide sales and revenue until the war concludes and the macroeconomic conditions recover. The Company generally does not invest any restaurant capital under a developmental license or affiliate arrangement, and it receives a royalty based on a percent of sales, and generally receives initial fees upon the opening of a new restaurant or grant of a new license."""

json_str = make_filing_json(
    ticker="MCD",
    cik="0000063908",
    company_name="McDonald's",
    filing_date="2025-02-25",
    accession="0000063908-25-000012",
    primary_doc="mcd-20241231.htm",
    item1=item1_text,
    item1a=item1a_text,
    item1b=item1b_text
)
# 파일로 저장하고 싶으면:
with open("json/business_json/GE.json", "w", encoding="utf-8") as f:
    f.write(json_str)